codecov:
  branch: develop
  bot: 132nd-etcher

coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    slack:
      default:
        url: "secret:zdv8K6Hxg69vulAKykwcrxW2vuGP1MRK0VK9ms9TYEspug+gz6jEQXtwtEJpUz20/FQuq77PvJpdzGS0Fkavx9Qaf3+giwmrpgGW1WL13+hRpake9cOZcWjIDIGtfkhGTt+Ov5thynhgTvsQZ5ZXWg6ndDBGRV5kCO7I9HrJgco="
        threshold: 1%
        branches:
          - master
          - develop
          - feature/*
        attachments: "sunburst, diff"

  ignore:
    - "tests"
    - "src/ui/skeletons"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches:
    - master
    - develop
    - prerelease
  behavior: default