doc-warnings: false
pep8:
  full: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
  - docs
  - tests
ignore-patterns:
  - ^__init__.py$
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 3