# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\DEV\EASI\EASIv0.0.11\src\ui\skeletons\form_mod_metadata.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(400, 384)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 15, 1, 1, 1)
        self.text_desc = QtWidgets.QTextBrowser(Form)
        self.text_desc.setReadOnly(False)
        self.text_desc.setAcceptRichText(False)
        self.text_desc.setObjectName("text_desc")
        self.gridLayout_2.addWidget(self.text_desc, 18, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 12, 0, 1, 1)
        self.label_help_version = QtWidgets.QLabel(Form)
        self.label_help_version.setOpenExternalLinks(True)
        self.label_help_version.setObjectName("label_help_version")
        self.gridLayout_2.addWidget(self.label_help_version, 10, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 11, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 17, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_help_name = QtWidgets.QLabel(Form)
        self.label_help_name.setObjectName("label_help_name")
        self.gridLayout_2.addWidget(self.label_help_name, 3, 1, 1, 1)
        self.combo_category = QtWidgets.QComboBox(Form)
        self.combo_category.setObjectName("combo_category")
        self.gridLayout_2.addWidget(self.combo_category, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 18, 0, 1, 1)
        self.edit_mod_name = QtWidgets.QLineEdit(Form)
        self.edit_mod_name.setMaxLength(48)
        self.edit_mod_name.setClearButtonEnabled(True)
        self.edit_mod_name.setObjectName("edit_mod_name")
        self.gridLayout_2.addWidget(self.edit_mod_name, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 16, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_version = QtWidgets.QLineEdit(Form)
        self.edit_version.setClearButtonEnabled(True)
        self.edit_version.setObjectName("edit_version")
        self.horizontalLayout_2.addWidget(self.edit_version)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 8, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_dcs_version = QtWidgets.QLineEdit(Form)
        self.edit_dcs_version.setClearButtonEnabled(True)
        self.edit_dcs_version.setObjectName("edit_dcs_version")
        self.horizontalLayout.addWidget(self.edit_dcs_version)
        self.gridLayout_2.addLayout(self.horizontalLayout, 12, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 19, 1, 1, 1)
        self.btn_increment_version = QtWidgets.QToolButton(Form)
        self.btn_increment_version.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_increment_version.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_increment_version.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btn_increment_version.setAutoRaise(False)
        self.btn_increment_version.setObjectName("btn_increment_version")
        self.gridLayout_2.addWidget(self.btn_increment_version, 9, 1, 1, 1)
        self.btn_pull_dcs_version = QtWidgets.QToolButton(Form)
        self.btn_pull_dcs_version.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_pull_dcs_version.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_pull_dcs_version.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btn_pull_dcs_version.setAutoRaise(False)
        self.btn_pull_dcs_version.setArrowType(QtCore.Qt.DownArrow)
        self.btn_pull_dcs_version.setObjectName("btn_pull_dcs_version")
        self.gridLayout_2.addWidget(self.btn_pull_dcs_version, 14, 1, 1, 1)
        self.edit_uuid = QtWidgets.QLineEdit(Form)
        self.edit_uuid.setAcceptDrops(False)
        self.edit_uuid.setReadOnly(True)
        self.edit_uuid.setObjectName("edit_uuid")
        self.gridLayout_2.addWidget(self.edit_uuid, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.edit_mod_name, self.combo_category)
        Form.setTabOrder(self.combo_category, self.edit_version)
        Form.setTabOrder(self.edit_version, self.edit_dcs_version)
        Form.setTabOrder(self.edit_dcs_version, self.text_desc)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Name"))
        self.label_7.setText(_translate("Form", "A \"*\" means \"this bit doesn\'t matter\"."))
        self.label_5.setText(_translate("Form", "Version"))
        self.label_6.setText(_translate("Form", "DCS version"))
        self.label_help_version.setText(_translate("Form", "<html><head/><body><p>The version must be a valid <a href=\"http://semver.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">SemVer</span></a>.</p></body></html>"))
        self.label_3.setText(_translate("Form", "Category"))
        self.label_2.setText(_translate("Form", "Unique ID"))
        self.label_help_name.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "Description"))
        self.label_8.setText(_translate("Form", "A \"+\" sign at the end means \"this version and all newer\"."))
        self.btn_increment_version.setText(_translate("Form", "Increment ..."))
        self.btn_pull_dcs_version.setText(_translate("Form", "Pull from ..."))

