# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\DEV\EASI\EASIv0.0.11\src\ui\skeletons\form_gh_login.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(695, 114)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_github_pic = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_github_pic.sizePolicy().hasHeightForWidth())
        self.label_github_pic.setSizePolicy(sizePolicy)
        self.label_github_pic.setMinimumSize(QtCore.QSize(32, 32))
        self.label_github_pic.setMaximumSize(QtCore.QSize(32, 32))
        self.label_github_pic.setText("")
        self.label_github_pic.setPixmap(QtGui.QPixmap(":/pic/github.png"))
        self.label_github_pic.setScaledContents(True)
        self.label_github_pic.setObjectName("label_github_pic")
        self.horizontalLayout.addWidget(self.label_github_pic)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_gh_create_account = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gh_create_account.sizePolicy().hasHeightForWidth())
        self.label_gh_create_account.setSizePolicy(sizePolicy)
        self.label_gh_create_account.setOpenExternalLinks(True)
        self.label_gh_create_account.setObjectName("label_gh_create_account")
        self.verticalLayout_10.addWidget(self.label_gh_create_account)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_gh_status_static = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gh_status_static.sizePolicy().hasHeightForWidth())
        self.label_gh_status_static.setSizePolicy(sizePolicy)
        self.label_gh_status_static.setObjectName("label_gh_status_static")
        self.horizontalLayout_3.addWidget(self.label_gh_status_static)
        self.label_gh_status = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gh_status.sizePolicy().hasHeightForWidth())
        self.label_gh_status.setSizePolicy(sizePolicy)
        self.label_gh_status.setMinimumSize(QtCore.QSize(200, 0))
        self.label_gh_status.setObjectName("label_gh_status")
        self.horizontalLayout_3.addWidget(self.label_gh_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.layout_gh_create_token = QtWidgets.QHBoxLayout()
        self.layout_gh_create_token.setObjectName("layout_gh_create_token")
        self.githubUsernameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.githubUsernameLabel.sizePolicy().hasHeightForWidth())
        self.githubUsernameLabel.setSizePolicy(sizePolicy)
        self.githubUsernameLabel.setObjectName("githubUsernameLabel")
        self.layout_gh_create_token.addWidget(self.githubUsernameLabel)
        self.githubUsernameLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.githubUsernameLineEdit.sizePolicy().hasHeightForWidth())
        self.githubUsernameLineEdit.setSizePolicy(sizePolicy)
        self.githubUsernameLineEdit.setObjectName("githubUsernameLineEdit")
        self.layout_gh_create_token.addWidget(self.githubUsernameLineEdit)
        self.githubPasswordLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.githubPasswordLabel.sizePolicy().hasHeightForWidth())
        self.githubPasswordLabel.setSizePolicy(sizePolicy)
        self.githubPasswordLabel.setObjectName("githubPasswordLabel")
        self.layout_gh_create_token.addWidget(self.githubPasswordLabel)
        self.githubPasswordLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.githubPasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.githubPasswordLineEdit.setSizePolicy(sizePolicy)
        self.githubPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.githubPasswordLineEdit.setObjectName("githubPasswordLineEdit")
        self.layout_gh_create_token.addWidget(self.githubPasswordLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_gh_create_token.addItem(spacerItem1)
        self.btn_gh_create = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_gh_create.sizePolicy().hasHeightForWidth())
        self.btn_gh_create.setSizePolicy(sizePolicy)
        self.btn_gh_create.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_gh_create.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_gh_create.setObjectName("btn_gh_create")
        self.layout_gh_create_token.addWidget(self.btn_gh_create)
        self.layout_gh_create_token.setStretch(1, 1)
        self.layout_gh_create_token.setStretch(3, 1)
        self.verticalLayout_10.addLayout(self.layout_gh_create_token)
        self.label_gh_tokens_http_link = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gh_tokens_http_link.sizePolicy().hasHeightForWidth())
        self.label_gh_tokens_http_link.setSizePolicy(sizePolicy)
        self.label_gh_tokens_http_link.setTextFormat(QtCore.Qt.RichText)
        self.label_gh_tokens_http_link.setOpenExternalLinks(True)
        self.label_gh_tokens_http_link.setObjectName("label_gh_tokens_http_link")
        self.verticalLayout_10.addWidget(self.label_gh_tokens_http_link)
        self.horizontalLayout.addLayout(self.verticalLayout_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_gh_create_account.setText(_translate("Form", "<html><head/><body><p>Don\'t have a Github account ? <a href=\"https://github.com/join\"><span style=\" text-decoration: underline; color:#0000ff;\">Create one here</span></a></p></body></html>"))
        self.label_gh_status_static.setText(_translate("Form", "Status: "))
        self.label_gh_status.setText(_translate("Form", "Not connected"))
        self.githubUsernameLabel.setText(_translate("Form", "Username"))
        self.githubPasswordLabel.setText(_translate("Form", "Password"))
        self.btn_gh_create.setText(_translate("Form", "Create token"))
        self.label_gh_tokens_http_link.setText(_translate("Form", "<html><head/><body><p>You can see your active Github tokens at: <a href=\"https://github.com/settings/applications\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/settings/applications</span></a></p></body></html>"))

from src.ui.resources import qt_resource_rc
